# source functions
source("./config.R")
source("./helper.R")

####################################################
####################### UI ######################### 
#################################################### 
sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("Inputs", icon = icon("cog"), tabName = "Inputs_tab",
             badgeLabel = "needed", badgeColor = "black"),
    hidden(menuItem("Data analysis", icon = icon("tasks"), tabName = "data_tab")),
    hidden(menuItem("Supplement", icon = icon("tasks"), tabName = "sup_tab")),
    hidden(menuItem("Download / Export", icon = icon("print"), tabName = "Export_tab")),
    menuItem(" Help & Literature", icon = icon("info-circle"), tabName = "how_to_tab")
  ),
  withBusyIndicatorUI({
    actionButton("update", "Update Settings", 
                 class = "btn-primary",
                 style= "color: #fff; background-color: #04A85C; border-color: #068B4E"
                 ) # style = "color: #fff; background-color: #f45042; border-color: #ff1500"
  })
)

body <- dashboardBody(
  useShinyjs(),
  extendShinyjs(text = AppJS),
  tags$style(appCSS),
  tags$head(
    tags$link(rel = "stylesheet", type = "text/css", href = "custom.css")
  ),
  tabItems(
    
    
    ############################################## Inputs_tab ######################################
    tabItem(tabName = "Inputs_tab",
            h1(tags$strong("Wormtracker Vol 0.94, alpha release")),
            h5(tags$em("(code name 'butterfly')")),
            tags$br(),

            tags$h2(tags$strong(tags$span(style="color:#04A85C", "A) Upload datasets"))),
            fluidRow(
              # upload box
              box(title = tags$strong("Upload data"),width = 8,status = "success",solidHeader = TRUE,
                  fileInput("upload_report", "Choose Report CSV File (auto-generated by the machine)",
                            accept = c(
                              "text/csv",
                              "text/comma-separated-values,text/plain",
                              ".csv")),
                  fileInput("upload_loading", "Choose Loading XLSX File",
                            accept = c(
                              "text/csv",
                              "text/comma-separated-values,text/plain",
                              ".csv",
                              ".xlsx")),
                  div(style="display: inline-block;vertical-align:middle; width: 150px;",actionButton("upload_finished", "Load / Reload Files", style= "color: #fff; background-color: #04A85C; border-color: #068B4E"))
                  # div(style="display: inline-block;vertical-align:middle; width: 150px;",uiOutput("UI_fast_download"))
              ),
              
              box(title = tags$em("Adjust import (after upload)"),width = 4,collapsible = TRUE,collapsed = TRUE,
                  tabsetPanel(type = "tabs",
                              tabPanel("Color", 
                                       tags$br(),
                                       uiOutput("UI_exclude_colors")
                              ),
                              tabPanel("Linetype", 
                                       tags$br(),
                                       uiOutput("UI_exclude_cond")
                              ),
                              tabPanel("Wells", 
                                       tags$br(),
                                       uiOutput("UI_exclude_IDs")
                              )
                  )
              )
            ),
            tags$br(),
            tags$br(),
            tags$br(),
            tags$h2(tags$strong(tags$span(style="color:#04A85C", "B) Select settings"))),
            fluidRow(
              box(id = "box_plot_settings",title = tags$strong("Plot settings"),width = 8,status = "success",solidHeader = FALSE,collapsible = TRUE,collapsed = TRUE,
                tabsetPanel(type = "tabs",
                  tabPanel("Control color", 
                           tags$br(),
                           tabPanel("Control groups", 
                                    uiOutput("UI_ctr_color"),
                                    tags$br(),
                                    uiOutput("UI_ctr_cond"),
                                    tags$br(),
                                    tags$em("Color settings"),
                                    tags$hr(),
                                    colourInput("ctr_color_color", "Control color color", value = "black", allowTransparent = TRUE),
                                    tags$br(),
                                    tags$em("Line settings"),
                                    tags$hr(),
                                    column(6, sliderInput("size_ctr",label = "Relative line thickness of control",min = 0,max = 10,value = c(2), step = 0.1, post = " x magnified")),
                                    column(6,  sliderInput("size_overall",label = "Overall line thickness",min = 0,max = 3,value = c(1), step = 0.1)),
                                    tags$br()
                                    )
                  ),
                  tabPanel("Panels",
                           tags$br(),
                            prettyRadioButtons("facet_rows", "Rows: select facet",status = "success",
                                         choiceNames = list("None","Color","Linetype","Stressor"),
                                         choiceValues = c(".","Color","Linetype","Stressor"),selected = ".",inline = TRUE),
                            tags$br(),
                            prettyRadioButtons("facet_cols", "Columns: select facet",status = "success",
                                         choiceNames = list("None","Color","Linetype","Stressor"),
                                         choiceValues = c(".","Color","Linetype","Stressor"),selected = "Color",inline = TRUE),
                            tags$br()
                  ),
                  tabPanel("Styling",
                           tags$br(),
                           uiOutput("UI_color_col"),
                           tags$br(),
                           prettyRadioButtons("appearance_selected", "Plot appearance",status = "success",
                                              choices  = list("Publication" = "appearance_publ", "Presentation (white)" = "appearance_pres_white", "Presentation (black)" = "appearance_pres_black", "Presentation (transparent)"="appearance_pres_trans"),selected = "appearance_publ",inline = TRUE),
                           tags$br(),
                           sliderInput("keywidth",label = "How long should the legend key be?",min = 1,max = 5,value = 2)
                           
                  ),

                  tabPanel("Axis range", 
                           tags$br(),
                           prettyRadioButtons("time_unit", "Rescale X-axis",status = "success",
                                              choices  = list("Minutes" = "minutes", "Hours" = "hours", "Days" = "days"),selected = "minutes",inline = TRUE),
                           tags$em("Clip X- and Y-axis"),
                           tags$hr(),
                          column(6,sliderInput("x_coord_range",label = "X-axis",min = 0,max = 5000,value = c(0,5000), step = 10, post = " min")),
                          column(6,sliderInput("y_coord_range",label = "Y-axis",min = -10,max = 700,value = c(0,700), step = 5, post = " a.u.")),
                          materialSwitch(inputId = "modify_axis",label = "Apply axis clipping?", value = FALSE,status = "success")

                  ),
                  tabPanel("Output option", 
                           tags$br(),    
                           materialSwitch(inputId = "filename_timestamp",label = "Add timestamp to all output files?", value = TRUE,status = "success"),
                           tags$br()    
                  )
                  )
              ),
              
              
              box(title = tags$em("Tune parameters"),width = 4,collapsible = TRUE,collapsed = TRUE,
                  tabsetPanel(type = "tabs",
                              tabPanel("Define death", 
                                       tags$br(),
                                       prettyRadioButtons("thresholding", "What to do with animals that do not move?",status = "success",
                                                          choiceNames = list("No threshold","Set all to 0","Filter"),
                                                          choiceValues = c("NONE","ZERO","FILTER"),
                                                          selected = "ZERO",inline = TRUE),
                                       sliderInput("ntimes_under_threshold",label = "How many times under threshold until an animal is out?",min = 1,max = 5,value = 2),
                                       sliderInput("rollmean_activity_threshold",label = "Rollmean activity smoothing",min = 5,max = 30,value = 20)
                                       
                              ),
                              tabPanel("Rescale", 
                                       tags$br(),
                                       textInput("rescale_to_value", "To which number should the activity be rescaled?", value = "not_specified", width = NULL), 
                                       textInput("use_timepoint_to_scale", "At what timepoint should the rescaling be performed?", value = 30, width = NULL, placeholder = 30),
                                       tags$em("The timepoint should be specified according to the time unit that was selected (minutes, hours, days).")
                              ),

                              tabPanel("Fit", 
                                       tags$br(),
                                       prettyRadioButtons("include_bolz_fit", "Select fit",status = "success",
                                                          choiceNames = list("Bolzmann fit (requires high-quality data)","Dynamic averaging (very robust)"),
                                                          choiceValues = c(TRUE,FALSE),selected = "FALSE",inline = TRUE),
                                       materialSwitch(inputId = "top_free",label = "Free startingpoint for Bolzmann fit?", value = TRUE,status = "success"),
                                       tags$hr(),
                                       sliderInput("activity_padding",label = "Blurr effect on activity threshold (padding)",min = 0.01,max = 0.1,value = 0.05),
                                       sliderInput("time_padding",label = "Blurr effect on activity threshold (padding)",min = 5,max = 15,value = 10)
                              )
                  )
              )
            ),
            tags$br(),
            tags$br(),
            tags$br(),
            tags$hr(style="border-color: #CACED7;"),
            fluidRow(
              box(title = tags$em("How to use this web tool"),width = 12,collapsible = TRUE,collapsed = TRUE,
                  tags$ol(
                    tags$li("Please visit the", tags$strong(tags$span(style="color:#04A85C", "Help & Literature section")) ,"(tab on the left), here you can find:"),
                      tags$ol(
                        tags$li("A video tutorial explaining the core functionality of the application."),
                        tags$li("A step by step protocol including example datasets."),
                        tags$li("The FAQ section answering the most frequent issues.")
                      ),
                    tags$br(),
                    tags$li("If the output cannot be downloaded or the videos do not display correctly please try another browser"),
                    tags$ol(
                      tags$li(tags$a(href = "https://www.google.com/chrome/", "Google Chrome")," is recommended for the best performance.")
                    ),
                    tags$br(),
                    tags$li("If you cannot generate your plots after following the points above and in the help section please reach out by raising a github issue.")
                  )
              )
            )
    ), 
    
    ############################################## Data Analysis ######################################
    tabItem(tabName = "data_tab",
            h1(tags$strong("Stress survival analysis")),
            
            
            tabsetPanel(
              tabPanel("Stressor only", 
                       tags$br(),
                       tags$h3(tags$strong("Raw well activities overlayed with group fit")),
                       plotOutput("p_Ars_rawline_fitted") %>% withSpinner(color = spinner_col,color.background = spinner_bg,type = 2),
                       tags$br(),
                       tags$br(),
                       tags$h3(tags$strong("Experiment groups")),
                       plotOutput("p_Ars_grpline") %>% withSpinner(color = spinner_col,color.background = spinner_bg,type = 2),
                       tags$br(),
                       tags$br(),
                       tags$br(),
                       tags$br(),
                       box(id = "box_plot_explan",title = tags$em("Plot explanation"),width = 12,solidHeader = FALSE,collapsible = TRUE,collapsed = TRUE,
                           tags$p("The movement score of the animals is depicted as a function of time. A fit line (either LOESS or Boltzmann) was drawn for each unique combination of parameters and colored as well as dashed accordingly. 
                                  The activity levels of each well are shown in thinner grey lines giving an impression of the observed heterogeneity within the measurements. 
                                  The fitted lines are readily affected by outlier wells and they should be removed beforehand using the tool provided (see Help & Literature section).
                                  LOESS (local polynomial regression is a very robust smoothing function which can be applied to nearly all datasets. However, it does not apply any restrictions on the expected shape of the fitting curve.
                                  The Bolzmann fit can only be applied to homogenous high-quality datasets and makes the assumption that the activity decreases to a stable level over time."),
                           tags$p("Median activity levels for all wells per group (one standard deviation shown as vertical lines)")
                                  ),
                       tags$em("plots can be downloaded directly from this page or in the Download & Export section.")
              ),
              tabPanel("All wells", 
                       tags$h4("Overlayed with a fit for each group"),
                       plotOutput("p_M9Ars_rawline_fitted") %>% withSpinner(color = spinner_col,color.background = spinner_bg,type = 2),
                       tags$br(),
                       tags$br(),
                       tags$h3(tags$strong("Experiment groups")),
                       tags$p("Median activity levels for all wells per group (one standard deviation shown as vertical lines)"),
                       plotOutput("p_M9Ars_grpline") %>% withSpinner(color = spinner_col,color.background = spinner_bg,type = 2)
              )
            )
            
    ),
  
    
    ############################################## Supplement ######################################
    tabItem(tabName = "sup_tab",
            h1(tags$strong("Extended figures")),
            
            tabsetPanel(
              tabPanel("Stressor only", 
                       tags$h3(tags$strong("Individual wells")),
                       tags$h4("Raw"),
                       plotOutput("p_Ars_rawline") %>% withSpinner(color = spinner_col,color.background = spinner_bg,type = 2)
              ),
              tabPanel("All wells", 
                       tags$h3(tags$strong("Individual wells")),
                       tags$h4("Raw"),
                       plotOutput("p_M9Ars_rawline") %>% withSpinner(color = spinner_col,color.background = spinner_bg,type = 2)
              ),
              tabPanel("Browse individual wells", 
                       tags$h3(tags$strong("Interactive well selection")),
                       tags$h4("Hover over the plot to identify outliers"),
                       plotlyOutput("p_reactive",height = "1500px") %>% withSpinner(color = spinner_col,color.background = spinner_bg,type = 2)
              )
            )
    ),
  
  ############################################## Download & Export ######################################
  tabItem(tabName = "Export_tab",
          h1(tags$strong("Export")),
          h3(div("Tables as combined Excel file (",tags$em("xlsx"), ")")),
          fluidRow(
            box(title = "Excel tables",width = 12,solidHeader = TRUE,status = "success",
                "Download statistics and all analysis inputs",
                tags$br(),tags$hr(),
                downloadBttn("excel_stats","Generate Excel file",color = "success",size = "md")
            )),
          
          h3(div("Plot collections (",tags$em("select preferred format"), ")")),
          fluidRow(
            box(width = 12,title = "Images",status = "success",solidHeader = TRUE,
                tags$div("For any change to take effect please", tags$strong("press the Update button"), "in the sidebar. Download all relevant images already grouped into folders.",tags$em("Transparency"),"is supported by the", tags$em("png"), "and", tags$em("tiff"), "format."), 
                tags$hr(),
                column(6,sliderInput("plot.width",label = "width (cm)",min = 2,max = 50,value = 40,post = " cm"),
                       prettyRadioButtons("plot.format", "plot format?",status = "success",
                                            choiceNames = list("png","jpeg","tiff","ps","pdf","svg"),
                                            choiceValues = c("png","jpeg","tiff","ps","pdf","svg"),selected = "pdf",inline = TRUE)
                       
                       ),
                column(6,     
                       sliderInput("plot.height",label = "height (cm)",min = 2,max = 50,value = 18,post = " cm"),
                       sliderInput("plot.dpi",label = "resolution (dpi)",min = 50,max = 2000,value = 600, post = " dpi")
                       ),
                tags$br(),tags$hr(),
                downloadBttn("download_zip_M9_Ars","M9 & Arsenite plots",color = "success",size = "md"),
                downloadBttn("download_zip_Ars","Arsenite plots",color = "success",size = "md")
            )
          ),
          
          h3(div("Combined R Objects (",tags$em("RDS"),")")),
          fluidRow(
            box(width = 12,title = "RDS file",status = "success",solidHeader = TRUE,
                "You can seamlessly continue the analysis by downloading the RDS file and loading it into your R session as described below.
                The RDS file contains all tables as well as the ggplot objects which can be directly modified to better suit your styling requirements.",
                tags$br(),
                tags$br(),
                tags$code("your_R_object <- readRDS('downloaded_RDS_file.rds')"),
                tags$br(),tags$hr(),
                downloadBttn("r_download","R download",color = "success",size = "md"))
            )
  ),
  
  
  ############################################## How to tab - help & information ######################################
  tabItem(tabName = "how_to_tab",
          
          h1(tags$strong("Help")),
          tags$br(),
          box(title = tags$strong("Video tutorials"),width = 12,status = "success",solidHeader = TRUE,
              tags$br(),
              tags$ol(
                tags$div(tags$strong(tags$span(style="color:#04A85C", "Q: Is there an example how to use this tool?"))),
                tags$div(tags$strong("A:"),"Yes, just download the example files in the section below and follow the video tutorial:", a(tags$strong("beginners tutorial (youtube)"), href=beginners_tutorial,target="_blank")),
                tags$br(),
                tags$div(tags$strong(tags$span(style="color:#04A85C", "Q: What do all the additional settings mean and how can I make use of them the most?"))),
                tags$div(tags$strong("A:"),"In this video you can learn everything about the non-default settings to enhance your analysis:", a(tags$strong("advanced options (youtube)"), href=advanced_options,target="_blank")),
                tags$br(),
                tags$div(tags$strong(tags$span(style="color:#04A85C", "Q: I have multiple experiments loaded on the same 96-well plate, can I separate them in the analysis?"))),
                tags$div(tags$strong("A:"),"Using individual loading files for each experiment you can perform independent evaluations as explained in this video:", a(tags$strong("multiple / mixed experiments (youtube)"), href=multiple_mixed_experiments,target="_blank")),
                tags$br(),
                tags$div(tags$strong(tags$span(style="color:#04A85C", "Q: How can the output (graphs and tables) be interpreted?"))),
                tags$div(tags$strong("A:"),"An example of how to generate knowledgeable insights from your output can be found here: ", a(tags$strong("interpreting results (youtube)"), href=interpreting_results,target="_blank")),
                tags$br(),
                tags$div(tags$strong(tags$span(style="color:#04A85C", "Q: How can the direct R-download option be used to customize the plots for presentations & publications?"))),
                tags$div(tags$strong("A:"),"Even if you are unfamiliar with R this video will help you to customize all plots successfully: ", a(tags$strong("R interface (youtube)"), href=R_interface,target="_blank"))
              )),
          
          box(title = tags$strong("Navigate the website"),width = 12,status = "success",solidHeader = TRUE,
          tags$br(),
          tags$ol(
            tags$li('Upload the Wormtracker report file (csv) as well as the loading file (xlsx) for the current experiment and then press the Update button in the sidebar.',
                    tags$br(),
                    tags$br(),
                    tags$div(tags$strong(tags$span(style="color:#04A85C", "If needed you can download the example dataset from here to complete the next steps of the tutorial: "))),
                    div(style="display: inline-block;vertical-align:right; width: 450px;",tags$br() ,downloadBttn("example_download","Example files",color = "success",size = "md"))
                    ),
            tags$br(),
            tags$li('Once your data has been parsed the Data analysis and Export tabs will be revealed.'),
            tags$br(),
            tags$li('Inspect the graphs displayed in the Data analysis tab, are they informative? If you would like to make changes (facet them by Color for example) then go back to the Inputs tab and alter the needed parameters and press the Update button in the sidebar - your plots will now be redrawn. To maximize the area to view your plots you can temporarily hide the sidebar by pressing on the symbol to the right of the Wormtracker title.'),
            tags$br(),
            tags$li('To save your work you have multiple options:'),
              tags$ol("download your input datasets, the assembled master table and the group statistics as an Excel file."),
              tags$ol("Save plots in thematically organized groups. If you want to modify the default plot parameters please press the Update button in the sidebar for the changes to take effect."),
              tags$ol("Save all R-objects used in this analysis (including all plots). You can customise them to better suit your needs."),
            tags$br(),
            tags$li('You can navigate the website freely (after the initial upload) but remember that you always need to press update in order for your changes to be incorporated.')
            )
          ),
          tags$br(),
          
          box(title = tags$strong("FAQ"),width = 12,status = "success",solidHeader = TRUE,
          tags$br(),
          tags$ol(
            tags$div(tags$strong(tags$span(style="color:#04A85C", "Q: The plot has more lines than I expect, what should I do?"))),
            tags$div(tags$strong("A:"),"You have multiple different groups in your analysis (e.g. different ages) and should either add this group as a facet or remove the unwanted groups in your loading Excel file and upload it again."),
            tags$br(),
            tags$div(tags$strong(tags$span(style="color:#04A85C", "Q: Certain fit lines go below zero while the activity data is strictly positive"))),
            tags$div(tags$strong("A:"),"Fitting methods can overshoot and thus result in negative fitted values. To avoid this problem select other fitting methods (e.g. Bolzmann sigmoidal fit) or alter the settings in the 'Low activity handling' section in the Data transformation input."),
            tags$br(),
            tags$div(tags$strong(tags$span(style="color:#04A85C", "Q: Bolzmann fit is not fitting the data"))),
            tags$div(tags$strong("A:"),"Sometimes the data cannot be accurately modelled (then no curve is drown). In most cases this is due to a failure to remove wells that are empty or otherwise resulting in abnormal activity timecourses, please review your excluded well selection on the Inputs tab."),
            tags$br(),
            tags$div(tags$strong(tags$span(style="color:#04A85C", "Q: How can I remove wells that are empty or erroneously pipetted?"))),
            tags$div(tags$strong("A:"),"Go to the Data analysis tab and go to the Well selection sub tab. Here, hover with the cursor hover over the plot and identify the wells that should be excluded. To zoom in click and drag over your selection. To zoom out double click anywhere on the plot."),
            tags$br(),
            tags$div(tags$strong(tags$span(style="color:#04A85C", "Q: I would like to have the Arsenite plots ovelayed and not facetted as the combined M9-Arsenite plots, what should I do?"))),
            tags$div(tags$strong("A:"),"If you only need the Arsenite plots then set the row and column settings in the 'Plot: Multipanel arrangement' on the Inputs tab to 'None'and export the Arsenite plots on the Export tab. If you would like to have Multipanel plots for M9-Arsenite AND non-facetted
                     plots for Arsenite-only then change the 'Plot: Multipanel arrangement' settings after exporting the first group of plots, press the update button and then export the other plot group with the changed multipanel settings."),
            tags$br(),
            tags$div(tags$strong(tags$span(style="color:#04A85C", "Q: I see no plots or the wrong plots on the data analysis tab, is the website broken?"))),
            tags$div(tags$strong("A:"),"Generating the plots requires up to 20 seconds depending on the size of your dataset and the number of groups. This also applies for updating the plots after you changed and updated your settings."),
            tags$br()
          )
          ),
          
          h1(tags$strong("Disclaimer")),
          tags$br(),
          box(title = tags$strong("Terms of service"),width = 12,status = "success",solidHeader = TRUE,
              tags$p("All the information available on this website (hereafter referred to as ‘app’) is published in good faith and for general information purpose only."),
              tags$p("We do not make any warranties about the accuracy, reliability, reproducibility and completeness of this information.Any action you take upon the information you find on this app is strictly at your own risk. will not be liable for any losses and/or damages in connection with the use of our app."),
              tags$p("From our app, you can visit other apps by following hyperlinks to such external sites. We have no control over the content and nature of these sites and we cannot take any responsibility over their content, privacy settings, terms of service or reliability."),
              tags$p("Please reference the original publication when you use any content or information generated through the app or its source code [manuscript under preparation]."),
              tags$div(tags$strong(tags$em(tags$span(style="color:#04A85C","By using our app, you hereby consent to our disclaimer and agree to its terms."))))
          ),
          
          tags$br(),
          h1(tags$strong("Bibliography")),
          tags$br(),
          box(title = tags$strong("Packages"),width = 12,status = "success",solidHeader = TRUE,
            tags$h4(tags$strong("Key packages used")),
            DT::dataTableOutput("key_citations"),
            tags$br(),
            tags$br(),
            tags$h4(tags$strong("Associated packages used")),
            DT::dataTableOutput("all_citations")
            ),
          tags$br(),
          tags$em("If you have any suggestions for the improvement of the app please contact us by raising a github issue.")
  )
))




# Put them together into a dashboardPage
ui <- dashboardPage(
  tags$head(tags$style(HTML("a {color: #3C8B52}"))),
  skin = "green", header = dashboardHeader(title = "Wormtracker"),sidebar = sidebar,body = body
)






### SERVER


server <- function(input, output) {
  
  
  ############################################## Inputs_tab ######################################
  
  observeEvent(input$upload_finished, {
    ############# Raw report ############ 
    import_raw <- import_file(path = input$upload_report)
    import_meta <- import_file(path = input$upload_loading)
    values$legend_titles <- wrangle_legendtitles(import_meta)
    dat_imp <- import_combine(import_raw = import_raw,import_meta = import_meta)
    # add info to reactive values:
    values$dat_imp <- dat_imp
    values$import_raw <- import_raw
    values$import_meta <- import_meta
    js$collapse("box_plot_settings")
  })
  
  
  
  
  observeEvent(input$update, {
    withBusyIndicatorServer("update", {
    dat <- values$dat_imp
    # remove selected colors and ages (if selected)
    if(!is.null(input$exclude_colors)) dat <- dat %>% filter(!Color %in% input$exclude_colors)
    if(!is.null(input$exclude_cond)) dat <- dat %>% filter(!Linetype %in% input$exclude_cond)
    if(!is.null(input$exclude_IDs)) dat <- dat %>% filter(!ID %in% input$exclude_IDs)

    # Convert time
    dat$time <- wrangle_convert_time(time = dat$time,prev = values$time_unit, change = input$time_unit)
    values$time_unit <- input$time_unit # save the change
    
    # Add AUC values
    dat <- dat %>% 
      group_by(ID) %>%
      mutate(AUC_ID = auc(time,activity))
    
    # activity threshold
    if(input$thresholding == "ZERO"){
      dat<- dat %>%
        group_by(ID) %>%
        arrange(time) %>%
        mutate(rollsum = RcppRoll::roll_mean(x = activity, n = input$ntimes_under_threshold,align = "right",fill = NA)) %>%
        mutate(activity = wrangle_threshold_set_0_activity(rollsum,activity,rollmean_activity_threshold = input$rollmean_activity_threshold)) %>%
        ungroup()
    }
    
    if(input$thresholding == "FILTER"){
      dat <- dat %>%
        group_by(ID) %>%
        arrange(time) %>%
        mutate(rollsum = RcppRoll::roll_mean(x = activity, n = input$ntimes_under_threshold,align = "right",fill = NA),
               keep = wrangle_threshold_filter(rollsum,rollmean_activity_threshold = input$rollmean_activity_threshold)) %>%
        filter(keep == TRUE) %>%
        ungroup()
    }
    
    # rescale
    if(!input$rescale_to_value == "not_specified") dat <- wrangle_rescale(dat,rescale_to_value = input$rescale_to_value, use_timepoint_to_scale = input$use_timepoint_to_scale)
    
    # add bolzmann sigmoidal predictions
    dat <- dat %>%
      group_by(Color,Linetype,Stressor) %>%
      mutate(y_pred_group = wrangle_bolz_sig(activity = activity,time = time, activity_padding = input$activity_padding, time_padding = input$time_padding, top_free = input$top_free)) %>%
      ungroup()
    
    # add average activity values for each sample
    averages <- dat %>% 
      dplyr::select(ID,activity,Color,Linetype,Stressor,time) %>%
      spread(key = ID,value = activity,sep = "_") %>%
      mutate(activity_mean = rowMeans(dplyr::select(.,starts_with("ID")),na.rm = TRUE))
    dat <- left_join(dat,averages, by = c("Color","Linetype","Stressor","time"))
    
    
    
    
    
    ############ create summary tables ############ 
    # 1.) create a complete PER WELL summary
    summary_nocomp <- wrangle_summarize_well(dat = dat, activity_padding = input$activity_padding, time_padding = input$time_padding)
    dat <- left_join(dat,summary_nocomp,by = c("ID"))
    
    # 1b) group-wise summary for plotting
    groups_for_plotting <- wrangle_summarize_groups(df = dat)
    dat <- left_join(dat,groups_for_plotting,by = c("Color","Linetype","Stressor"))
    
    # 2.) create a STRESSOR summary
    summary_stressor <- wrangle_summarize_stressor(dat)
    dat <- left_join(dat,summary_stressor,by = c("Color","Linetype","Stressor"))
    summary_stressor_styled <- dat %>% dplyr::select(Color,Linetype,Stressor,`Half-activity time AVG` : stressor_High95Conf) %>% distinct()
    summary_stressor_styled <- summary_stressor_styled %>% dplyr::rename(`Half-activity time` = `Half-activity time AVG`, `Half-activity activity` = `Half-activity activity AVG`, `p-value` = stressor_pval, `95% Conf. Int. Lower`  =  stressor_Low95Conf, `95% Conf. Int. Upper`  =  stressor_High95Conf)
  
    color_levels <- input$color_level_order
    cond_levels <- input$cond_level_order
    dat <- dat %>% mutate(Color = factor(as.character(Color),levels = color_levels),
                          Linetype = factor(as.character(Linetype),levels = cond_levels)) # previous strategy
    # add line scaling variable
    dat <- dat %>% mutate(ctr_vs_exp = "exp")
    dat[dat$Color == input$color_level_order[[1]],"ctr_vs_exp"] <- "control"
    
    
    


      


    
    
    
   
      
    

    
    # add Statistics information for every sample (averaged corresponding wells)
    # summary_stressor_add <- summary_stressor %>%
    #   rename('Half-activity time AVG' = 'Half-activity time',
    #          'Half-activity activity AVG' = 'Half-activity activity') %>%
    #   select(Color,Stressor,Age,'Half-activity time AVG', 'Half-activity activity AVG')
    # dat <- left_join(dat,summary_stressor_add,by = c("Color", "Stressor","Age"))
    
    # # UNDER DEVELOPMENT: COMPARISON TO CONTROL:
    # dat_stats <- dat %>%
    #   ungroup() %>%
    #   select(ID:Stressor,Mean:Max) %>%
    #   distinct()
    # 
    # dat_stats %>%
    #   group_by(Color,Age,RNAi,Stressor) %>%
    #   mutate(Mean_mean = mean(Mean,na.rm = TRUE),
    #          Mean_sd = sd(Mean,na.rm = TRUE),
    #          Mean_ste = sd(Mean,na.rm = TRUE)/sqrt(length(Mean[!is.na(Mean)])),
    #          HAT_mean = mean(`Half-activity time`,na.rm = TRUE),
    #          HAT_sd = sd(`Half-activity time`,na.rm = TRUE),
    #          HAT_ste = sd(`Half-activity time`,na.rm = TRUE)/sqrt(length(`Half-activity time`[!is.na(`Half-activity time`)])),
    #          HAA_mean = mean(`Half-activity activity`,na.rm = TRUE),
    #          HAA_sd = sd(`Half-activity activity`,na.rm = TRUE),
    #          HAA_ste = sd(`Half-activity activity`,na.rm = TRUE)/sqrt(length(`Half-activity activity`[!is.na(`Half-activity activity`)]))
    #          )
    
    # for excel output: combine wells with standard deviations
    
    
    # summary <- summary_nocomp %>% filter(Stressor == levels(dat$Stressor)[2]) %>% select(Color:`Half-activity activity`)
    # control_Color <- levels(dat$Color)[length(levels(dat$Color))]
    # summary_rel_to_ctr <- wrangle_comp_to_control(summary,control_Color)
    # 

    
    
    
    

  
    
    ############ Plots ############ 
    ### Color palette
    if(!is.null(input$color_palette)) values$color_palette <- input$color_palette
    if(values$color_palette %in% c("viridis","plasma")) pal <- viridis(n = length(unique(dat$Color)),option = values$color_palette)
    if(values$color_palette %in% c("ggplot_style")) pal <-  hue_pal()(length(unique(dat$Color)))
    if(values$color_palette %in% c("pal_Cyril1","pal_Cyril2","pal_subway","colorblind","deuteranopia","protanopia","tritanopia")) pal <- pal_manual[[values$color_palette]]
    names(pal) <- unique(dat$Color)
    # Assign the control Color & color
    print("Control color order")
    print(input$color_level_order)
    print("first entry")
    print(input$color_level_order[[1]])
    values$color_level_order <- input$color_level_order
    ctr_idx <-  names(pal) %in% input$color_level_order[[1]]
    pal[ctr_idx] <- input$ctr_color_color
    if(!is.null(input$cond_level_order)) values$cond_level_order <- input$cond_level_order
    
    
    ### Size palette
    size <- c("control" = input$size_overall * input$size_ctr,"exp" = input$size_overall)
    ### Set theme and legend
    theme <- themes[[input$appearance_selected]]
    style_legends <- set_legend_style(keywidth = input$keywidth, legend_titles = values$legend_titles)
    style_legend <- style_legends[[input$appearance_selected]]
    
    # linetype palette
    lty <- 1:n_distinct(dat$Linetype)
    names(lty) <- levels(dat$Linetype)
    
    # aggregate input information
    facet_info <- paste0(input$facet_rows," ~ ",input$facet_cols)
    p_str <- list(plot.format = input$plot.format, plot.dpi = input$plot.dpi,plot.width = input$plot.width, 
                  plot.height = input$plot.height, filename_timestamp = input$filename_timestamp,
                  modify_axis = input$modify_axis, x_coord_range = input$x_coord_range, y_coord_range = input$y_coord_range,
                  facet_info = facet_info,
                  size = size,
                  pal = pal,
                  lty = lty)
    
    ###### M9 and arsenite
    p <- ggplot(data = dat %>% mutate(Color = fct_rev(Color), Linetype = fct_rev(Linetype)), aes(x = time, y = activity, 
                                group = ID, 
                                shape = Stressor,
                                linetype = Linetype,
                                color = Color,
                                size = ctr_vs_exp,
                                alpha = Stressor)) +
      labs(title = "Activity in individual wells", x = paste0("Time [",input$time_unit,"]"), y = "Movement score [a.u.]")
    p_M9Ars_rawline <- p +
      geom_line()
    values$p_M9Ars_rawline <- plot_modif(p_M9Ars_rawline,p_str,size_scale = 0.4,style_legend = style_legend) + theme()

    p_M9Ars_rawline_bolzFit <- p +
      geom_line(alpha = 0.4, size = 0.4) +
      geom_line(aes(x = time,y = y_pred_group,size = ctr_vs_exp))
    values$p_M9Ars_rawline_bolzFit <- plot_modif(p_M9Ars_rawline_bolzFit,p_str,size_scale = 1,style_legend = style_legend) + theme()

    p_M9Ars_rawline_smoothFit <- p +
      geom_smooth(se = F,span = 0.1, size = 0.7, color = "grey") + #bg lines
      # geom_smooth(aes(group = interaction(Linetype,Color,Stressor)), linetype = 0, span=0.7) + # only the confidence interval
      geom_line(stat = "smooth",method = "loess",aes(group = interaction(Linetype,Color,Stressor), color = Color),span=0.7) # the smoothed line, no interval
    values$p_M9Ars_rawline_smoothFit <- plot_modif(ggobj = p_M9Ars_rawline_smoothFit,p_str,size_scale = 1,style_legend = style_legend) + theme()

    p_group <- ggplot(data = dat %>% mutate(Color = fct_rev(Color), Linetype = fct_rev(Linetype)), 
                      aes(x = time, 
                          y = activity,
                          group = interaction(Linetype,Color,Stressor),
                          shape = Stressor,
                          color = Color,
                          size = ctr_vs_exp,
                          linetype =  Linetype,
                          alpha = Stressor)) +
      labs(title = "Activity for each group", x = paste0("Time [",input$time_unit,"]"), y = "Movement score [a.u.]")

    p_M9Ars_grpline <- p_group +
      stat_summary(fun.data="stat_one_sigma", geom="linerange", size = 0.4) +
      stat_summary(fun.data="stat_median", geom="line")
    values$p_M9Ars_grpline <- plot_modif(p_M9Ars_grpline,p_str,size_scale = 0.8, style_legend = style_legend)  + theme()


    p_line_half_activity <- p + 
      geom_line() +
      geom_point(aes(x = `HAT_perWell`, y = `HAA_perWell`)) +
      geom_point(aes(x = `Half-activity time AVG`, y = `Half-activity activity AVG`), size = 9) +
      scale_shape_manual(values = c(9,10)) + 
      labs(title = "Half-activity time diagnostic plot",subtitle = "Half-activity is marked for each well and their combination (large)", x = paste0("Time [",input$time_unit,"]"), y = "Movement score [a.u.]")
    values$p_line_half_activity <- plot_modif(p_line_half_activity,p_str,size_scale = 0.5,style_legend = style_legend)  + theme()

    ###### Only arsenite
    dat_ars <- dat %>% filter(Stressor != "M9") 
    p <- ggplot(
      data = dat_ars %>% mutate(Color = fct_rev(Color), Linetype = fct_rev(Linetype)),
      aes(
        x = time,
        y = activity,
        group = ID,
        color = Color,
        size = ctr_vs_exp,
        linetype =  Linetype
      )
    ) +
      labs(
        title = "Activity in individual wells",
        x = paste0("Time [", input$time_unit, "]") ,
        y = "Movement score [a.u.]"
      )
    
    
    p_Ars_rawline <- p +
      geom_line()
    values$p_Ars_rawline <- plot_modif(p_Ars_rawline,p_str,size_scale = 0.4,style_legend = style_legend)  + theme()

    p_Ars_rawline_bolzFit <- p +
      geom_line(alpha = 0.4) +
      geom_line(aes(x = time,y = y_pred_group))
    values$p_Ars_rawline_bolzFit <- plot_modif(p_Ars_rawline_bolzFit,p_str,size_scale = 1,style_legend = style_legend)  + theme()
    
    p_Ars_rawline_smoothFit <- p +
      geom_smooth(se = F,span = 0.1, size = 0.7, color = "grey") + #bg lines
      # geom_smooth(aes(group = interaction(Linetype,Color,Stressor)), linetype = 0, span=0.7) + # only the confidence interval
      geom_line(stat = "smooth",method = "loess",aes(group = interaction(Linetype,Color,Stressor), color = Color),span=0.7) # the smoothed line, no interval
    values$p_Ars_rawline_smoothFit <- plot_modif(p_Ars_rawline_smoothFit,p_str,size_scale = 1,style_legend = style_legend)  + theme()
    values$p_Ars_quickdown <- values$p_Ars_rawline_smoothFit + coord_cartesian(ylim = c(), xlim = p_str$x_coord_range)
    
    p_group <- ggplot(data = dat_ars %>% mutate(Color = fct_rev(Color), Linetype = fct_rev(Linetype)), 
                      aes(x = time, 
                          y = activity,
                          group = interaction(Linetype,Color),
                          color = Color,
                          size = ctr_vs_exp,
                          linetype =  Linetype)) +
      labs(title = "Combined well activities", x = paste0("Time [",input$time_unit,"]") , y = "Movement score [a.u.]")
    
    
    p_Ars_grpline <- p_group +
      stat_summary(fun.data="stat_one_sigma", geom="linerange", size = 0.4) +
      stat_summary(fun.data="stat_median", geom="line")
    values$p_Ars_grpline <- plot_modif(p_Ars_grpline,p_str,size_scale = 0.8,style_legend = style_legend)  + theme()
    
    # reactive
    values$p_reactive <- ggplotly(values$p_M9Ars_rawline, tooltip="group") %>% config(displayModeBar = F) %>% hide_legend()
    
    # add info to reactive values:
    values$dat <- dat
    values$summary_stressor_styled <- summary_stressor_styled
    values$p_str <- p_str
    

    # Show other tabs
    if (nrow(dat) > 1) {
      shinyjs::show(selector = "ul li:eq(1)", anim = TRUE) # orig: selector = "ul li:eq(1)"
      delay(ms = 270,expr =  shinyjs::show(selector = "ul li:eq(2)", anim = TRUE)) # orig: selector = "ul li:eq(2)"
      delay(ms = 270,expr =  shinyjs::show(selector = "ul li:eq(3)", anim = TRUE)) # added for additional ta
      
    }
    
    output$UI_fast_download <- renderUI({
      downloadButton("fast_download","Fast - download")
    })
    
  })
  })
  
  
  
  
  
  
  # ReactiveValues
  values <- reactiveValues(import_raw = NULL, import_meta = NULL, legend_titles = NULL,dat_imp = NULL, dat = NULL, summary_stressor_styled = NULL,
                           # processed inputs
                           p_str = NULL,
                           # M9Ars plots
                           p_M9Ars_rawline = NULL,  p_M9Ars_rawline_bolzFit = NULL, p_M9Ars_rawline_smoothFit = NULL,
                           p_M9Ars_grpline = NULL,
                           # rs plots
                           p_Ars_rawline = NULL,  p_Ars_rawline_bolzFit = NULL, p_Ars_rawline_smoothFit = NULL,
                           p_Ars_grpline = NULL,
                           # reactive
                           p_reactive = NULL,
                           # tables
                           summary_ctrvsexp = NULL,
                           # SELECTED input:
                           time_unit = "minutes",
                           color_level_order = "",
                           cond_level_order = "",
                           color_palette = "ggplot_style"
                           )
  
  
  
  ############################################## Data analysis ######################################

  
  # M9 and Arsenite
  output$p_M9Ars_rawline <- renderPlot({
    values$p_M9Ars_rawline + plot_shiny_theme
  },bg="transparent")
  output$p_M9Ars_rawline_fitted <- renderPlot({
    if(input$include_bolz_fit) {plot <- values$p_M9Ars_rawline_bolzFit 
    }else{plot <- values$p_M9Ars_rawline_smoothFit}
    plot + plot_shiny_theme
  },bg="transparent")
  output$p_M9Ars_grpline <- renderPlot({
    values$p_M9Ars_grpline + plot_shiny_theme
  },bg="transparent")
  # Only Arsenite
  output$p_Ars_rawline <- renderPlot({
    values$p_Ars_rawline + plot_shiny_theme
  },bg="transparent")
  output$p_Ars_rawline_fitted <- renderPlot({
    if(input$include_bolz_fit) {plot <- values$p_Ars_rawline_bolzFit 
    }else{plot <- values$p_Ars_rawline_smoothFit}
    plot + plot_shiny_theme
  },bg="transparent")
  output$p_Ars_grpline <- renderPlot({
    values$p_Ars_grpline + plot_shiny_theme
  },bg="transparent")
  # reactive
  output$p_reactive <- renderPlotly({
    values$p_reactive
  })
  
  
  ################## Input Table
  output$UI_exclude_colors <- renderUI({
    tags$div(align = "left",
             class = "multicol", 
    awesomeCheckboxGroup(inputId = "exclude_colors",label = "Colors",inline = TRUE, status = "success",
                       h3("Checkbox group"),
                       choices = unique(as.character(values$dat_imp$Color)))
  )})
  output$UI_exclude_cond <- renderUI({
    tags$div(align = "left",
             class = "multicol", 
    awesomeCheckboxGroup(inputId = "exclude_cond",label = "Linetype",inline = TRUE, status = "success",
                       h3("Checkbox group"),
                       choices = unique(values$dat_imp$Linetype))
  )})
  output$UI_exclude_IDs <- renderUI({
    tags$div(align = "left",
             class = "multicolmany", 
    awesomeCheckboxGroup(inputId = "exclude_IDs",label = "Wells",inline = TRUE, status = "success",
                       h3("Checkbox group"),
                       choices = unique(values$dat_imp$ID))
  )})
  
  # Set Color control groups & Color color
  output$UI_ctr_color <- renderUI({
    if(values$color_level_order != "") {
      choices <-values$color_level_order
    } else {
      choices <- unique(as.character(values$dat_imp$Color))
    }
    orderInput(inputId = 'color_level', label = 'Order colors', items = choices)
  })
  
  # Set color control groups & color color
  output$UI_ctr_cond <- renderUI({
    # choices <- if(is.null(values$dat)) {unique(as.character(values$dat_imp$Linetype))} else{unique(as.character(values$dat$Linetype))}
    # tags$div(align = "left",
    #          prettyRadioButtons("ctr_cond","Select control  Linetype", status = "success",
    #                             choices = choices,selected = values$ctr_cond,inline = TRUE)
    
    if(values$cond_level_order != "") {
      choices <-values$cond_level_order
    } else {
      choices <- unique(as.character(values$dat_imp$Linetype))
    }
    orderInput(inputId = 'cond_level', label = 'Order linetypes', items = choices)
    })
  
  output$UI_color_col <- renderUI({
    choices <- list("Default"="ggplot_style", "Viridis"="viridis","Plasma"="plasma","Accented"="pal_Cyril1","Deep colors"="pal_Cyril2","NYC Subways"="pal_subway","CB for all subtypes"="colorblind","CB (deuteranopia)"="deuteranopia","CB (protanopia)"="protanopia","CB (tritanopia)"="tritanopia")
    if(length(unique(values$dat$Color)) > 12) {
      choices <- list("Default"="ggplot_style","Viridis"="viridis","Plasma"="plasma")
    }
    prettyRadioButtons("color_palette", "Color palette ('CB' = color blind):",status = "success",
                 choices = choices,
                 selected = values$color_palette,inline = TRUE)
  })
  
  
  
  ############################################## Download & Export ######################################
  
  output$fast_download <- downloadHandler(
    filename = function() {
      name <- "Fast_download_output.zip"
      ifelse(input$filename_timestamp,paste0(Sys.Date(),"_",name),name)
    },
    content = function(file) {
      tmpdir <- tempdir()
      setwd(tempdir())

      p_str_half <- values$p_str
      p_str_half$plot.width <- c(40)
      p_str_half$plot.height <- c(30)
      p_str_half$facet_info <- "Color ~ ."
      p_str_ars <- values$p_str
      p_str_ars$plot.width <- c(40)
      p_str_ars$plot.height <- c(20)
      p_str_ars$facet_info <- ". ~ ."
      p_str_list <- list(p_str_half,p_str_ars)

      p_list <- list(p_line_half_activity = values$p_line_half_activity,
                     p_Ars_quickdown = values$p_Ars_quickdown)
      
      names <- list()
      for (idx in 1:length(p_list)) {
        names[idx] <- export_plot(plot = p_list[idx],p_str = p_str_list[[idx]],appearance_selected = input$appearance_selected)
      }

      zipr(zipfile=file, files= unlist(names))
      if(file.exists(paste0(file, ".zip"))) {file.rename(paste0(file, ".zip"), file)}
    },
    contentType = "application/zip"
  )
  
  output$excel_stats <- downloadHandler(
    filename = function() {ifelse(input$filename_timestamp,paste0(Sys.Date(),"_","Wormtracker.xlsx"),"Wormtracker.xlsx")},
    content = function(file) {
      tab_summary_lty_Ars <- wrangle_summarize_control(df = values$dat %>% filter(Stressor != "M9"),col_label = Linetype, Color)$tab_summary
      tab_summary_col_Ars <- wrangle_summarize_control(df = values$dat %>% filter(Stressor != "M9"),col_label = Color, Linetype)$tab_summary
      tab_summary_lty_M9 <- wrangle_summarize_control(df = values$dat %>% filter(Stressor == "M9"),col_label = Linetype, Color)$tab_summary
      tab_summary_col_M9 <- wrangle_summarize_control(df = values$dat %>% filter(Stressor == "M9"),col_label = Color, Linetype)$tab_summary
      tab_summary_lty_all <- wrangle_summarize_control(df = values$dat %>% mutate(Stressor = factor(Stressor,levels = levels(values$dat$Stressor)[c(2,1)])),col_label = Linetype, Stressor, Color)$tab_summary
      tab_summary_col_all <- wrangle_summarize_control(df = values$dat %>% mutate(Stressor = factor(Stressor,levels = levels(values$dat$Stressor)[c(2,1)])),col_label = Color, Stressor, Linetype)$tab_summary
      pval_out <- wrangle_summarize_pvalmatrix(df = values$dat)
      values$summary_ctrvsexp <- list(tab_summary_lty_Ars = tab_summary_lty_Ars,
                                      tab_summary_col_Ars = tab_summary_col_Ars,
                                      tab_summary_lty_M9 = tab_summary_lty_M9,
                                      tab_summary_col_M9 = tab_summary_col_M9,
                                      tab_summary_lty_all = tab_summary_lty_all,
                                      tab_summary_col_all = tab_summary_col_all,
                                      pval_values = pval_out$pval_mat_vals,
                                      pval_symbol = pval_out$pval_mat_symb,
                                      pval_stressor_values = pval_out$pval_mat_vals_stressor,
                                      pval_stressor_symbol = pval_out$pval_mat_symb_stressor
                                      )
      raw_meta <- values$import_meta
      colnames(raw_meta) <- NULL
      export_tables(ctrvsexp = values$summary_ctrvsexp,
                    processed_movement = values$dat %>% select(ID,Color,Linetype,Stressor,time,AUC_ID,activity_mean) %>% spread(key = time,value = activity_mean),
                    raw_meta = raw_meta,
                    file = file,
                    filename_timestamp = input$filename_timestamp)
    }
  )
  
  # download R files
  output$r_download <- downloadHandler(
    filename = function() {ifelse(input$filename_timestamp,paste0(Sys.Date(),"_","Robjects.rds"),"Robjects.rds")},
    content = function(file) {
      values_export <- reactiveValuesToList(values)
      saveRDS(object =  values_export,file = file)
    }
  )


  
  output$download_zip_M9_Ars <- downloadHandler(
    filename = function() {
      name <- "M9_Arsenite_output.zip"
      ifelse(input$filename_timestamp,paste0(Sys.Date(),"_",name),name)
      },
    content = function(file) {
      tmpdir <- tempdir()
      setwd(tempdir())
      p_list <- list(p_M9Ars_rawline = values$p_M9Ars_rawline, 
                     p_M9Ars_rawline_smoothFit = values$p_M9Ars_rawline_smoothFit, 
                     p_M9Ars_grpline = values$p_M9Ars_grpline)
      if(input$include_bolz_fit) p_list["p_M9Ars_rawline_bolzFit"] <- values$p_M9Ars_rawline_bolzFit

      names <- list()
      for (idx in 1:length(p_list)) {
        names[idx] <- export_plot(plot = p_list[idx],p_str = values$p_str,appearance_selected = input$appearance_selected)
      }
      zipr(zipfile=file, files=unlist(names))
      if(file.exists(paste0(file, ".zip"))) {file.rename(paste0(file, ".zip"), file)}
    },
    contentType = "application/zip"
  )
  
  output$download_zip_Ars <- downloadHandler(
    filename = function() {
      name <- "Arsenite_output.zip"
      ifelse(input$filename_timestamp,paste0(Sys.Date(),"_",name),name)
      },
    content = function(file) {
      tmpdir <- tempdir()
      setwd(tempdir())
      p_list <- list(p_Ars_rawline = values$p_Ars_rawline, 
                     p_Ars_rawline_smoothFit = values$p_Ars_rawline_smoothFit, 
                     p_Ars_grpline = values$p_Ars_grpline)
      if(input$include_bolz_fit) p_list["p_Ars_rawline_bolzFit"] <- values$p_Ars_rawline_bolzFit
      
      names <- list()
      for (idx in 1:length(p_list)) {
        names[idx] <- export_plot(plot = p_list[idx],p_str = values$p_str,appearance_selected = input$appearance_selected)
      }
      zipr(zipfile=file, files=unlist(names))
      if(file.exists(paste0(file, ".zip"))) {file.rename(paste0(file, ".zip"), file)}
    },
    contentType = "application/zip"
  )
  
  ############################################## Download & Export ######################################

    
  ############################################## How to tab - help & information ######################################
  
  output$key_citations <- DT::renderDataTable({
    df <- wrangle_full_bib(packages = key_packages)
    DT::datatable(df,rownames= FALSE,options = list( 
      pageLength = 50, dom = 't'
    )) %>%  DT::formatStyle(columns = c(1:ncol(df)), fontSize = '120%')
  })
  
  output$all_citations <- DT::renderDataTable({
    df <- wrangle_full_bib(packages = CRAN_packageList)
    DT::datatable(df,rownames= FALSE,options = list( 
      pageLength = 50, dom = 'ft'
    )) %>%  DT::formatStyle(columns = c(1:ncol(df)), fontSize = '80%')
  })
  
  # download example files
  output$example_download <- downloadHandler(
    filename = function() {ifelse(input$filename_timestamp,paste0(Sys.Date(),"_","example_files.zip"),"example_files.zip")},
    content = function(file) {
      zipr(zipfile=file, files=c("report.csv","loading.xlsx")) #place files in same directory as app.R
    },
    contentType = "application/zip"
  )
  

}

### APP
shinyApp(ui, server) 

